services:
  - type: web
    name: xeno-channel-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CRM_RECEIPT_URL
        value: https://xeno-crm-ry0s.onrender.com/api/receipts
